name: FlareAndQuests
main: com.patrickzhong.faqFlareAndQuests
version: 3
author: ShowbizLocket61

commands:
  faq:
    description: Main command for FlareAndQuests
    usage: /<command>
  rq: 
    description: Main command for Rank Quests
    usage: /<command>
  flare: 
    description: Main command for Flares
    usage: /<command>
  witem: 
    description: Main command for Witems
    usage: /<command>