name: FlareAndQuests
main: com.drizzard.faq.FlareAndQuests
version: ${project.version}
author: ShowbizLocket61
softdepend: [Factions]

commands:
  faq:
    description: Main command for FlareAndQuests
    usage: /<command>
    permission: faq.faq
  rq: 
    description: Main command for Rank Quests
    usage: /<command>
    permission: faq.rq
  flare: 
    description: Main command for Flares
    usage: /<command>
    permission: faq.flare
  witem: 
    description: Main command for Witems
    usage: /<command>
    permission: faq.witem
  mm:
    description: Main command for Mystery Mobs
    usage: /<command>
    permission: faq.mm