name: FlareAndQuests
main: com.drizzard.faq.FlareAndQuests
version: 4.1.9.4
author: ShowbizLocket61

commands:
  faq:
    description: Main command for FlareAndQuests
    usage: /<command>
    permission: faq.faq
  rq: 
    description: Main command for Rank Quests
    usage: /<command>
    permission: faq.rq
  flare: 
    description: Main command for Flares
    usage: /<command>
    permission: faq.flare
  witem: 
    description: Main command for Witems
    usage: /<command>
    permission: faq.witem

permissions:
  faq.*:
    description: All FlareAndQuests permissions
    default: op
    children:
      faq.faq: true
      faq.rq: true
      faq.flare: true
      faq.witem: true
  faq.faq:
    description: Gives access to the /faq command
    default: op
  faq.rq:
    description: Gives access to the /rq command
    default: op
  faq.flare:
    description: Gives access to the /flare command
    default: op
  faq.witem:
    description: Gives access to the /witem command
    default: op